# Generated by Django 4.1.2 on 2022-10-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DmVCourtStats",
            fields=[
                (
                    "court_alias",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("total_rows", models.IntegerField(blank=True, null=True)),
                ("min_dt", models.DateField(blank=True, null=True)),
                ("max_dt", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "dm_v_court_stats",
                "ordering": ["court_alias"],
                "managed": False,
            },
        ),
    ]
