###################################################################################################
#
#     Docker Composer file for starting up Courts Info Service Bot.
#
#     Created:  Dmitrii Gusev, 13.11.2022
#     Modified:
#
###################################################################################################

# docker services to run
services:
  courtsbot:
    container_name: courtsinfo-bot-container
    image: courtsbot
    build: .
    restart: unless-stopped
    networks:
      - bot_network
    # environment:
    #   ENV_NAME: ENV_VALUE
    # ports:
    #   - "port:port" # DBMS port

# network configuration
networks:
  bot_network:
    driver: bridge
    name: bot-network
